"""A deterministic, offline, free generator -- a fixture, never a result.

It exists so the harness can be exercised end to end with no API key and no
network: the whole test suite runs on it, and so does any `heal-yield run`
invoked without `--yes-spend`. It measures nothing about a model, and in
particular it has NOT been used to fix the per-candidate time limit or the
per-run USD ceiling -- both are declared-as-unset (see METRICS.md).

Everything it emits is marked `"fixture": true` in its usage record, the
harness propagates that into `run.json`, and a fixture run is mechanically
barred from being a headline repetition. Numbers produced with this generator
describe the harness, not a model.

It is scripted rather than random so that a run is reproducible byte for byte:

  * one test that always passes,
  * one test per public callable asserting it is callable (passes),
  * one test that fails at round 0 and is repaired at round 1,
  * one test that fails in every round (never heals),
  * one test, in a file that never imports the module, that passes but covers
    nothing new (no-coverage-increase),
  * optionally one that weakens itself under repair, to exercise the guard.
"""

from __future__ import annotations

import ast
import os
from typing import List, Optional

from ._contract import parse_args, read_source, write_meta

MODEL = "stub-fixture-generator/1"


def public_callables(source: str) -> List[str]:
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    names = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if not node.name.startswith("_"):
                names.append(node.name)
    return names[:6]


def render(module: str, names: List[str], round_index: int, weaken: bool) -> str:
    lines = [
        "# generated by heal-yield stub_gen -- FIXTURE, not a model result",
        "import importlib",
        "",
        "import pytest",
        "",
        "MOD = importlib.import_module(%r)" % module,
        "",
        "",
        "def test_module_imports():",
        "    assert MOD is not None",
        "",
    ]
    for i, name in enumerate(names):
        lines += [
            "",
            "def test_%s_is_public():" % _safe(name),
            "    obj = getattr(MOD, %r, None)" % name,
            "    assert obj is not None",
            "    assert not %r.startswith('_')" % name,
            "",
        ]

    # Fails at round 0, repaired from round 1 onward.
    expected = "1" if round_index >= 1 else "2"
    lines += [
        "",
        "def test_repairable_arithmetic():",
        "    assert len([0]) == %s" % expected,
        "",
    ]

    # Never heals, in any round.
    lines += [
        "",
        "def test_never_heals():",
        "    assert getattr(MOD, 'definitely_not_a_real_attribute') is None",
        "",
    ]

    if weaken and round_index >= 1:
        lines += ["", "def test_guard_bait():", "    assert True", ""]
    elif weaken:
        lines += ["", "def test_guard_bait():", "    assert MOD is not None",
                  "    assert 1 == 2", ""]

    lines.append("")
    lines.append("_ = pytest")
    lines.append("")
    return "\n".join(lines)


def _safe(name: str) -> str:
    return "".join(c if c.isalnum() or c == "_" else "_" for c in name).lower()


def main(argv: Optional[List[str]] = None) -> int:
    args = parse_args(argv)
    source = read_source(args.repo, args.source_file)
    weaken = os.environ.get("HEAL_YIELD_STUB_WEAKEN") == "1"
    code = render(args.module, public_callables(source), args.round, weaken)

    os.makedirs(args.out_dir, exist_ok=True)
    name = "test_%s.py" % args.module.replace(".", "_")
    with open(os.path.join(args.out_dir, name), "w") as fh:
        fh.write(code)

    # A second file that never imports the module under test: it passes and
    # covers nothing new, which is the `no-coverage-increase` disposition.
    isolated = "test_%s_isolated.py" % args.module.replace(".", "_")
    with open(os.path.join(args.out_dir, isolated), "w") as fh:
        fh.write(
            "# generated by heal-yield stub_gen -- FIXTURE, not a model result\n"
            "def test_covers_nothing_new():\n"
            "    assert sum(range(4)) == 6\n"
        )

    write_meta(
        args.meta_out,
        MODEL,
        prompt_tokens=0,
        completion_tokens=0,
        usd=0.0,
        extra={"fixture": True, "round": args.round},
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
